"""Tests for matools.io – file reading/writing helpers."""

import gzip
import textwrap
from pathlib import Path

import pandas as pd
import pytest

from matools.io import (
    MAF_REQUIRED_COLS,
    read_bed,
    read_maf,
    read_tsv,
    read_vcf,
    write_maf,
    write_tsv,
)


# ---------------------------------------------------------------------------
# Fixtures – synthetic in-memory files written to tmp_path
# ---------------------------------------------------------------------------

MAF_CONTENT = textwrap.dedent(
    """\
    #version 2.4
    # Generated by matools tests
    Hugo_Symbol\tChromosome\tStart_Position\tEnd_Position\tVariant_Classification\tVariant_Type\tReference_Allele\tTumor_Seq_Allele1\tTumor_Seq_Allele2\tTumor_Sample_Barcode
    TP53\t17\t7674220\t7674220\tMissense_Mutation\tSNP\tC\tC\tT\tSAMPLE_01
    KRAS\t12\t25398284\t25398284\tMissense_Mutation\tSNP\tC\tC\tA\tSAMPLE_01
    BRCA1\t17\t41276040\t41276040\tNonsense_Mutation\tSNP\tG\tG\tT\tSAMPLE_02
    """
)

VCF_CONTENT = textwrap.dedent(
    """\
    ##fileformat=VCFv4.2
    ##FILTER=<ID=PASS,Description="All filters passed">
    #CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO
    chr1\t925952\t.\tG\tA\t.\tPASS\t.
    chr7\t140453136\t.\tA\tT\t.\tPASS\t.
    """
)

BED_CONTENT = textwrap.dedent(
    """\
    # track name="example"
    chr1\t0\t1000\tregion_A
    chr2\t500\t1500\tregion_B
    """
)

TSV_CONTENT = textwrap.dedent(
    """\
    # comment line
    sample\tgene\texpression
    S1\tTP53\t2.3
    S2\tKRAS\t5.1
    """
)


@pytest.fixture()
def maf_file(tmp_path):
    p = tmp_path / "test.maf"
    p.write_text(MAF_CONTENT)
    return p


@pytest.fixture()
def maf_gz_file(tmp_path):
    p = tmp_path / "test.maf.gz"
    with gzip.open(p, "wt") as fh:
        fh.write(MAF_CONTENT)
    return p


@pytest.fixture()
def vcf_file(tmp_path):
    p = tmp_path / "test.vcf"
    p.write_text(VCF_CONTENT)
    return p


@pytest.fixture()
def bed_file(tmp_path):
    p = tmp_path / "test.bed"
    p.write_text(BED_CONTENT)
    return p


@pytest.fixture()
def tsv_file(tmp_path):
    p = tmp_path / "test.tsv"
    p.write_text(TSV_CONTENT)
    return p


# ---------------------------------------------------------------------------
# MAF tests
# ---------------------------------------------------------------------------

class TestReadMaf:
    def test_returns_dataframe(self, maf_file):
        df = read_maf(maf_file)
        assert isinstance(df, pd.DataFrame)

    def test_row_count(self, maf_file):
        df = read_maf(maf_file)
        assert len(df) == 3

    def test_required_columns_present(self, maf_file):
        df = read_maf(maf_file)
        for col in MAF_REQUIRED_COLS:
            assert col in df.columns, f"Missing column: {col}"

    def test_comment_lines_skipped(self, maf_file):
        df = read_maf(maf_file)
        assert df.iloc[0]["Hugo_Symbol"] == "TP53"

    def test_reads_gzipped(self, maf_gz_file):
        df = read_maf(maf_gz_file)
        assert len(df) == 3

    def test_gene_values(self, maf_file):
        df = read_maf(maf_file)
        assert set(df["Hugo_Symbol"]) == {"TP53", "KRAS", "BRCA1"}


class TestWriteMaf:
    def test_roundtrip(self, maf_file, tmp_path):
        df = read_maf(maf_file)
        out = tmp_path / "out.maf"
        write_maf(df, out)
        df2 = read_maf(out)
        assert list(df.columns) == list(df2.columns)
        assert len(df) == len(df2)

    def test_comment_header_written(self, maf_file, tmp_path):
        df = read_maf(maf_file)
        out = tmp_path / "out.maf"
        write_maf(df, out, comment_header="version 2.4")
        content = out.read_text()
        assert content.startswith("#version")

    def test_write_gz(self, maf_file, tmp_path):
        df = read_maf(maf_file)
        out = tmp_path / "out.maf.gz"
        write_maf(df, out)
        df2 = read_maf(out)
        assert len(df) == len(df2)


# ---------------------------------------------------------------------------
# VCF tests
# ---------------------------------------------------------------------------

class TestReadVcf:
    def test_returns_tuple(self, vcf_file):
        result = read_vcf(vcf_file)
        assert isinstance(result, tuple) and len(result) == 2

    def test_header_lines(self, vcf_file):
        headers, _ = read_vcf(vcf_file)
        assert all(h.startswith("##") for h in headers)
        assert len(headers) == 2

    def test_variant_dataframe(self, vcf_file):
        _, df = read_vcf(vcf_file)
        assert isinstance(df, pd.DataFrame)
        assert len(df) == 2
        assert "CHROM" in df.columns


# ---------------------------------------------------------------------------
# BED tests
# ---------------------------------------------------------------------------

class TestReadBed:
    def test_returns_dataframe(self, bed_file):
        df = read_bed(bed_file)
        assert isinstance(df, pd.DataFrame)

    def test_base_columns(self, bed_file):
        df = read_bed(bed_file)
        assert "chrom" in df.columns
        assert "chromStart" in df.columns
        assert "chromEnd" in df.columns

    def test_row_count(self, bed_file):
        df = read_bed(bed_file)
        assert len(df) == 2

    def test_numeric_coords(self, bed_file):
        df = read_bed(bed_file)
        assert df["chromStart"].dtype == int
        assert df["chromEnd"].dtype == int

    def test_extra_col_named(self, bed_file):
        df = read_bed(bed_file, extra_cols=["name"])
        assert "name" in df.columns


# ---------------------------------------------------------------------------
# TSV tests
# ---------------------------------------------------------------------------

class TestReadTsv:
    def test_returns_dataframe(self, tsv_file):
        df = read_tsv(tsv_file)
        assert isinstance(df, pd.DataFrame)

    def test_comment_skipped(self, tsv_file):
        df = read_tsv(tsv_file)
        assert "sample" in df.columns

    def test_row_count(self, tsv_file):
        df = read_tsv(tsv_file)
        assert len(df) == 2


class TestWriteTsv:
    def test_roundtrip(self, tsv_file, tmp_path):
        df = read_tsv(tsv_file)
        out = tmp_path / "out.tsv"
        write_tsv(df, out)
        df2 = pd.read_csv(out, sep="\t")
        assert list(df.columns) == list(df2.columns)
        assert len(df) == len(df2)
